"use client";
import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
import { Toaster } from "sonner";
import Header from "./components/Header";
import Footer from "./components/Footer";
import { usePathname } from "next/navigation";

const dmSans = DM_Sans({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-dm-sans",
});

// export const metadata: Metadata = {
//   title: "Tutor Platform",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${dmSans.className} flex flex-col`}>
        <main className="mx-auto w-full h-full justify-center items-center">
          <Providers>{children}</Providers>
        </main>
        <Toaster richColors closeButton />
      </body>
    </html>
  );
}
