"use client"
import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
import { Toaster } from "sonner";
import Header from "./components/Header";
import Footer from "./components/Footer";
import { usePathname } from "next/navigation";

const dmSans = DM_Sans({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-dm-sans",
});

// export const metadata: Metadata = {
//   title: "Tutor Platform",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();
  const isHomepage = pathname === "/";
  return (
    <html lang="en">
      <body
        className={`${dmSans.className} flex flex-col`}
        >
        <Header/>
        <main className={`${isHomepage ? "" : "flex-1 pt-[4%]" }`}>
        <Providers>{children}</Providers>
        </main>
        <Toaster richColors closeButton />
        <Footer/>
      </body>
    </html>
  );
}
